name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      PYTHON_VERSION:
        required: true
        type: string
      TOX_MIN_VERSION:
        required: true
        type: string

defaults:
  run:
    shell: bash

# See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#updating-your-github-actions-workflow
permissions:
  id-token: write # required for requesting the JWT
  contents: read  # required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ inputs.PYTHON_VERSION }}"
          cache: 'pip'
          cache-dependency-path: setup.py
      - name: Install dependencies
        run: |
          pip install "tox>=${{ inputs.TOX_MIN_VERSION }}"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME_ARN }}
          role-session-name: ${{ github.actor }}
      - name: Convert secrets and vars to environment variables
        shell: python
        run: |
          import os

          secrets_and_vars = {
              **${{ toJson(secrets) }},
              **${{ toJson(vars) }},
          }

          with open(os.environ["GITHUB_ENV"], "a") as env_file:
              for name, value in secrets_and_vars.items():
                  # If the value contains a newline, use the delimiter syntax
                  # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#multiline-strings
                  if "\n" in value:
                      print(f"{name}<<EOF\n{value}\nEOF", file=env_file)
                  else:
                      # Standard format for single lines
                      print(f"{name}={value}", file=env_file)
      - name: Deploy forward notification to ${{ inputs.environment }}
        run: |
          make deploy-forward
