name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

defaults:
  run:
    shell: bash

env:
  AWS_REGION: us-west-2

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install tox
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Export secrets as environment variables
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          while read -rd $'' line
          do
            echo "$line" >> $GITHUB_ENV
          done < <(jq -r <<<"$SECRETS_CONTEXT" \
            'to_entries|map("\(.key)=\(.value)\u0000")[]')
      - name: Deploy to ${{ inputs.environment }}
        run: make deploy
