# Install Python dependencies, run tests, and lint with a single version of Python.
# See https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HLS LPDAAC Historical

on:
  release:
    types:
      - published
  push:
    branches:
      - main
      - develop
    tags-ignore:
      - '*'
    paths:
      - 'cdk/**'
      - 'src/**'
      - 'cdk.json'
      - 'Makefile'
      - 'setup.py'
      - 'tox.ini'
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - develop
    paths:
      - 'cdk/**'
      - 'src/**'
      - 'cdk.json'
      - 'Makefile'
      - 'setup.py'
      - 'tox.ini'

defaults:
  run:
    shell: bash

jobs:
  constants:
    # This is a hack to work around the lack of support for two other possiblities for
    # avoiding duplication of configuration values:
    #
    # (1) YAML anchors (https://yaml.org/spec/1.1/current.html#id899912) and aliases
    #     (https://yaml.org/spec/1.1/current.html#id902561)
    # (2) Availability of `env` context within `jobs.<job-id>.with.<with-id>` (see
    #     https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability)
    #
    # Alternative hack: https://github.com/actions/runner/issues/1182#issuecomment-1262870831
    runs-on: ubuntu-22.04
    outputs:
      PYTHON_VERSION: "3.9"
      TOX_MIN_VERSION: "3.18.0"  # `allowlist_externals` replaces `whitelist_externals`
    steps:
      - name: Define constants
        run: ""  # Nothing to do, but at least one step is required

  unit-tests:
    runs-on: ubuntu-22.04
    needs: constants
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ needs.constants.outputs.PYTHON_VERSION }}"
      - name: Install dependencies
        run: |
          pip install "tox>=${{ needs.constants.outputs.TOX_MIN_VERSION }}"
      - name: Run unit tests
        run: |
          make unit-tests

  integration-tests:
    if: >-
      (github.event_name == 'pull_request' && (github.base_ref == 'develop' || github.base_ref == 'main')) ||
      (github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main')) ||
      (github.event_name == 'release')
    runs-on: ubuntu-22.04
    needs:
      - constants
      - unit-tests
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ needs.constants.outputs.PYTHON_VERSION }}"
      - name: Install dependencies
        run: |
          pip install "tox>=${{ needs.constants.outputs.TOX_MIN_VERSION }}"
      - name: Run integration tests
        run: |
          make ci-deploy
          # Ensure stack is destroyed at exit, even if tests fail
          trap "make ci-destroy" EXIT
          make integration-tests

  deploy-dev:
    # Deploy to Dev only on push (including merged PR) to `develop` branch
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/develop'
    needs:
      - constants
      - integration-tests
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      PYTHON_VERSION: "${{ needs.constants.outputs.PYTHON_VERSION }}"
      TOX_MIN_VERSION: "${{ needs.constants.outputs.TOX_MIN_VERSION }}"
    secrets: inherit

  deploy-prod:
    # Deploy to Prod only on publishing a release (tag) on `main` branch
    if: github.event_name == 'release' && github.event.action == 'published'
    needs:
      - constants
      - integration-tests
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      PYTHON_VERSION: "${{ needs.constants.outputs.PYTHON_VERSION }}"
      TOX_MIN_VERSION: "${{ needs.constants.outputs.TOX_MIN_VERSION }}"
    secrets: inherit
